apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: syfomotebehov-alerts
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  receivers:
    slack:
      channel: '#esyfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: SYFOMOTEBEHOV IS DOWN!
      expr: up{app="syfomotebehov", job="kubernetes-pods"} == 0
      for: 5m
      description: "App syfomotebehov er nede"
      action: "Undersøk hvofor syfomotebehov er nede"
      severity: danger
    - alert: HIGH RATIO OF HTTP 5XX RESPONSE
      expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^5\\d\\d", service="syfomotebehov"}[5m]))) / (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfomotebehov"}[5m])))) > 2
      for: 5m
      description: "App syfomotebehov har en høy andel 500 feil "
      action: "Sjekk i Grafana eller logger hvorfor syfomotebehov returnerer mange 500-feil"
      severity: danger
    - alert: HIGH RATIO OF HTTP 4XX RESPONSE
      expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^4\\d\\d", service="syfomotebehov"}[5m]))) / (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfomotebehov"}[5m])))) > 10
      for: 5m
      description: "App syfomotebehov har en høy 400 feil"
      action: "Sjekk i Grafana eller logger hvorfor syfomotebehov returnerer mange 400-feil"
      severity: warning
    - alert: KAFKA ISOPPFOLGINGSTILFELLE-TOPIC CONSUMER LAG
      expr: kafka_consumergroup_group_topic_sum_lag{topic="teamsykefravr.isoppfolgingstilfelle-oppfolgingstilfelle-person", group="syfomotebehov-p-isoppfolgingstilfelle"} > 0
      for: 15m
      description: "syfomotebehov har ukonsumerte Kafkameldinger på isoppfolgingstilfelle-topic"
      action: "Finn ut hvorfor syfomotebehov har stoppet å konsumere fra topic"
      severity: danger
