apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomotebehov
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfomotebehov/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfomotebehov/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1536Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfomotebehov/internal/prometheus
  ingresses:
    - "https://syfomotebehov.intern.nav.no"
    - "https://syfomotebehov.nais.adeo.no"
    - "https://app.adeo.no/syfomotebehov"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfomotebehov.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/prod/creds/syfomotebehov_p-user"
        mountPath: "/secrets/syfomotebehovdb/credentials"
      - kvPath: "/oracle/data/prod/config/syfomotebehov_p"
        mountPath: "/secrets/syfomotebehovdb/config"
      - kvPath: "/kv/prod/fss/syfomotebehov/team-esyfo"
        mountPath: "/var/run/secrets/nais.io/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "syfomotebehov"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: toggle_enable_nullstill
      value: 'false'
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: AKTORREGISTER_REST_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.nais.adeo.no
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.adeo.no
    - name: NO_NAV_SECURITY_JWT_ISSUER_INTERN_DISCOVERYURL
      value: https://isso.adeo.no:443/isso/oauth2/.well-known/openid-configuration
    - name: KAFKA_ENV_NAME
      value: p
