apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomotebehov
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfomotebehov/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfomotebehov/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfomotebehov/internal/prometheus
  ingresses:
    - "https://syfomotebehov.dev.intern.nav.no"
    - "https://syfomotebehov.nais.preprod.local"
    - "https://app-q1.adeo.no/syfomotebehov"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfomotebehov.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/dev/creds/syfomotebehov_q1-user"
        mountPath: "/secrets/syfomotebehovdb/credentials"
      - kvPath: "/oracle/data/dev/config/syfomotebehov_q1"
        mountPath: "/secrets/syfomotebehovdb/config"
      - kvPath: "/kv/preprod/fss/syfomotebehov/team-esyfo"
        mountPath: "/var/run/secrets/nais.io/vault"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: APP_NAME
      value: "syfomotebehov"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: toggle_enable_nullstill
      value: 'false'
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: AKTORREGISTER_REST_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.nais.preprod.local
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.preprod.local/syfo-tilgangskontroll/api/tilgang
    - name: ESYFOVARSELAPI_URL
      value: https://esyfovarsel.dev.adeo.no/api/bruker
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: SYFOBEHANDLENDEENHET_URL
      value: https://syfobehandlendeenhet.nais.preprod.local
    - name: NO_NAV_SECURITY_JWT_ISSUER_INTERN_DISCOVERYURL
      value: https://isso-q.adeo.no:443/isso/oauth2/.well-known/openid-configuration
    - name: KAFKA_ENV_NAME
      value: q1
