apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomotebehov
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /syfomotebehov/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfomotebehov/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfomotebehov/internal/prometheus
  ingresses:
    - "https://syfomotebehov.dev.intern.nav.no"
    - "https://syfomotebehov.dev-fss-pub.nais.io"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: dialogmote-frontend
          namespace: team-esyfo
          cluster: dev-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: dev-gcp
        - application: isyfomock
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: tms-min-side-proxy
          namespace: min-side
          cluster: dev-gcp
    outbound:
      rules:
        - application: isnarmesteleder
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfo-tilgangskontroll
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: dev-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://syfomotebehov.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/dev/creds/syfomotebehov_q1-user"
        mountPath: "/secrets/syfomotebehovdb/credentials"
      - kvPath: "/oracle/data/dev/config/syfomotebehov_q1"
        mountPath: "/secrets/syfomotebehovdb/config"
      - kvPath: "/kv/preprod/fss/syfomotebehov/team-esyfo"
        mountPath: "/var/run/secrets/nais.io/vault"
  kafka:
    pool: nav-dev
  env:
    - name: APP_NAME
      value: "syfomotebehov"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: toggle_enable_nullstill
      value: 'false'
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.intern.dev.nav.no
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.intern.dev.nav.no/syfo-tilgangskontroll/api/tilgang
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.preprod.local
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "https://syfobehandlendeenhet.intern.dev.nav.no"
    - name: KAFKA_ENV_NAME
      value: q1
    - name: DIALOGMOTE_FRONTEND_CLIENT_ID
      value: dev-gcp:team-esyfo:dialogmote-frontend
    - name: TMS_MIN_SIDE_PROXY_CLIENT_ID
      value: dev-gcp:min-side:tms-min-side-proxy
    - name: SYFOBRUKERTILGANG_CLIENT_ID
      value: dev-gcp:team-esyfo:syfobrukertilgang
    - name: DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID
      value: dev-gcp:flex:ditt-sykefravaer
    - name: ISNARMESTELEDER_URL
      value: "https://isnarmesteleder.intern.dev.nav.no"
    - name: ISNARMESTELEDER_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: SPRING_PROFILES_ACTIVE
      value: remote,testdatareset
