apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfomotebehov
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  startup:
    path: /syfomotebehov/internal/isAlive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 10
  liveness:
    path: /syfomotebehov/internal/isAlive
    initialDelay: 30
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /syfomotebehov/internal/isReady
    initialDelay: 30
    timeout: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 256Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfomotebehov/internal/prometheus
  ingresses:
    - "https://syfomotebehov.intern.dev.nav.no"
  tokenx:
    enabled: true
  leaderElection: true
  accessPolicy:
    inbound:
      rules:
        - application: esyfo-proxy
        - application: dialogmote-frontend
        - application: syfomodiaperson
          namespace: teamsykefravr
        - application: isyfomock
          namespace: teamsykefravr
        - application: ditt-sykefravaer
          namespace: flex
        - application: tms-min-side-proxy
          namespace: min-side
    outbound:
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
      rules:
        - application: esyfovarsel
        - application: syfobrukertilgang
        - application: istilgangskontroll
          namespace: teamsykefravr
        - application: syfobehandlendeenhet
          namespace: teamsykefravr
        - application: isnarmesteleder
          namespace: teamsykefravr
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - "NAVident"
  idporten:
    enabled: true
    sidecar:
      enabled: true
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: syfomotebehov-db
        diskAutoresize: true
  kafka:
    pool: nav-dev
  env:
    - name: APP_NAME
      value: "syfomotebehov"
    - name: KAFKA_ENV_NAME
      value: "q1"
    - name: DIALOGMOTE_FRONTEND_CLIENT_ID
      value: "dev-gcp:team-esyfo:dialogmote-frontend"
    - name: TMS_MIN_SIDE_PROXY_CLIENT_ID
      value: "dev-gcp:min-side:tms-min-side-proxy"
    - name: ESYFO_PROXY_CLIENT_ID
      value: "dev-gcp:team-esyfo:esyfo-proxy"
    - name: SYFOBRUKERTILGANG_CLIENT_ID
      value: "dev-gcp:team-esyfo:syfobrukertilgang"
    - name: DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID
      value: "dev-gcp:flex:ditt-sykefravaer"
    - name: PDL_CLIENT_ID
      value: "dev-fss.pdl.pdl-api"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll.teamsykefravr"
    - name: SYFOBRUKERTILGANG_CLIENT_ID
      value: "dev-gcp.team-esyfo.syfobrukertilgang"
    - name: SYFOBRUKERTILGANG_URL
      value: "http://syfobrukertilgang"
    - name: ESYFOVARSEL_CLIENT_ID
      value: "dev-gcp.team-esyfo.esyfovarsel"
    - name: ESYFOVARSEL_URL
      value: "http://esyfovarsel"
    - name: SYFOBEHANDLENDEENHET_CLIENT_ID
      value: "dev-gcp.teamsykefravr.syfobehandlendeenhet"
    - name: SYFOBEHANDLENDEENHET_URL
      value: "http://syfobehandlendeenhet.teamsykefravr"
    - name: ISNARMESTELEDER_CLIENT_ID
      value: "dev-gcp.teamsykefravr.isnarmesteleder"
    - name: ISNARMESTELEDER_URL
      value: "http://isnarmesteleder.teamsykefravr"
