REVOKE ALL ON ALL TABLES IN SCHEMA public FROM cloudsqliamuser;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO cloudsqliamuser;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cloudsqliamuser;
