-- -- Create the motebehovFormValues table
-- CREATE TABLE MOTEBEHOV_FORM_VALUES
-- (
--     form_snapshot                       JSONB       NOT NULL,
--     begrunnelse                         VARCHAR(1000),
--     onsker_sykmelder_deltar             BOOLEAN     NOT NULL,
--     onsker_sykmelder_deltar_begrunnelse VARCHAR(500),
--     onsker_tolk                         BOOLEAN     NOT NULL,
--     tolk_sprak                          VARCHAR(100),
--     motebehov_uuid                      VARCHAR(36) NOT NULL
-- );
--
-- -- Create an index on the id field
-- CREATE INDEX idx_motebehov_form_values_motebehov_uuid ON MOTEBEHOV_FORM_VALUES (motebehov_uuid);
--
-- -- Add the new foreign key constraint from motebehov_form_values to motebehov with ON DELETE CASCADE
-- ALTER TABLE MOTEBEHOV_FORM_VALUES
--     ADD CONSTRAINT fk_motebehov
--         FOREIGN KEY (motebehov_uuid)
--             REFERENCES MOTEBEHOV (motebehov_uuid)
--             ON DELETE CASCADE;