name: merge-dependabot-pr
on:
  workflow_dispatch:
  schedule:
    - cron: '0,15,30,45 7-14 * * 1,2,3,4,5'

jobs:
  merge-dependabot-pr:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/merge-dependabot-pr.yaml@main
    permissions:
      actions: write
      checks: read
      contents: write
      pull-requests: write
      statuses: read
